// <auto-generated />
namespace Token_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class adding_Employee_and_User_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_Employee_and_User_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202407281901274_adding_Employee_and_User_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
